// flow-typed signature: 97685d59f6c2b4593ccc2ebdc02019f3
// flow-typed version: <<STUB>>/eslint-config-bliss_v^1.0.8/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-bliss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-bliss' {
  declare module.exports: any;
}
