// flow-typed signature: 937587d636e24a36723ace31dd0fb465
// flow-typed version: <<STUB>>/falcon-core_v0.0.1-8/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'falcon-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'falcon-core' {
  declare module.exports: any;
}
