// flow-typed signature: 07d1f018c5c2b63f9d5f3f65ac3c78d0
// flow-typed version: <<STUB>>/react-json-pretty_v^1.6.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-json-pretty'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-json-pretty' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-json-pretty/example/app/Example' {
  declare module.exports: any;
}

declare module 'react-json-pretty/example/public/common' {
  declare module.exports: any;
}

declare module 'react-json-pretty/example/public/example' {
  declare module.exports: any;
}

declare module 'react-json-pretty/example/webpack.config' {
  declare module.exports: any;
}

declare module 'react-json-pretty/JSONPretty' {
  declare module.exports: any;
}

declare module 'react-json-pretty/src/JSONPretty' {
  declare module.exports: any;
}

declare module 'react-json-pretty/tests/pretty_js_snapshot.test' {
  declare module.exports: any;
}

declare module 'react-json-pretty/tests/pretty_jsx_snapshot.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-json-pretty/example/app/Example.jsx' {
  declare module.exports: $Exports<'react-json-pretty/example/app/Example'>;
}
declare module 'react-json-pretty/example/public/common.js' {
  declare module.exports: $Exports<'react-json-pretty/example/public/common'>;
}
declare module 'react-json-pretty/example/public/example.js' {
  declare module.exports: $Exports<'react-json-pretty/example/public/example'>;
}
declare module 'react-json-pretty/example/webpack.config.js' {
  declare module.exports: $Exports<'react-json-pretty/example/webpack.config'>;
}
declare module 'react-json-pretty/JSONPretty.jsx' {
  declare module.exports: $Exports<'react-json-pretty/JSONPretty'>;
}
declare module 'react-json-pretty/src/JSONPretty.js' {
  declare module.exports: $Exports<'react-json-pretty/src/JSONPretty'>;
}
declare module 'react-json-pretty/tests/pretty_js_snapshot.test.js' {
  declare module.exports: $Exports<
    'react-json-pretty/tests/pretty_js_snapshot.test'
  >;
}
declare module 'react-json-pretty/tests/pretty_jsx_snapshot.test.js' {
  declare module.exports: $Exports<
    'react-json-pretty/tests/pretty_jsx_snapshot.test'
  >;
}
